import { ReportRecord, KPIMitra } from "./types";

export const fallbackReports: ReportRecord[] = [
  // --- JULI 2025 ---
  { id: "juli-2025-al-falah-depok", bulan: "Juli", tahun: 2025, sekolahMitra: "Al-Falah Depok", tanggalKirim: "8-Dec-2025", statusLaporan: "Sudah Kirim", statusAudit: "Selesai" },
  { id: "juli-2025-al-falah-klaten", bulan: "Juli", tahun: 2025, sekolahMitra: "Al-Falah Klaten", tanggalKirim: "21-Nov-2025", statusLaporan: "Sudah Kirim", statusAudit: "Selesai" },
  { id: "juli-2025-athaillah", bulan: "Juli", tahun: 2025, sekolahMitra: "Athaillah", tanggalKirim: "23-Nov-2025", statusLaporan: "Sudah Kirim", statusAudit: "Selesai" },
  { id: "juli-2025-cordova", bulan: "Juli", tahun: 2025, sekolahMitra: "Cordova", tanggalKirim: "2-Dec-2025", statusLaporan: "Sudah Kirim", statusAudit: "Selesai" },
  { id: "juli-2025-haura", bulan: "Juli", tahun: 2025, sekolahMitra: "Haura", tanggalKirim: "28-Jul-2025", statusLaporan: "Sudah Kirim", statusAudit: "Selesai" },
  { id: "juli-2025-ibnu-sina", bulan: "Juli", tahun: 2025, sekolahMitra: "Ibnu Sina", tanggalKirim: "7-Aug-2025", statusLaporan: "Sudah Kirim", statusAudit: "Selesai" },
  { id: "juli-2025-ideal", bulan: "Juli", tahun: 2025, sekolahMitra: "Ideal", tanggalKirim: "3-Sep-2025", statusLaporan: "Sudah Kirim", statusAudit: "Selesai" },
  { id: "juli-2025-kamila", bulan: "Juli", tahun: 2025, sekolahMitra: "Kamila", tanggalKirim: "8-Jun-2026", statusLaporan: "Sudah Kirim", statusAudit: "Revisi" },
  { id: "juli-2025-sma-lazuardi", bulan: "Juli", tahun: 2025, sekolahMitra: "SMA Lazuardi", tanggalKirim: "", statusLaporan: "Belum Kirim", statusAudit: "-" },
  { id: "juli-2025-tursina", bulan: "Juli", tahun: 2025, sekolahMitra: "Tursina", tanggalKirim: "6-Aug-2025", statusLaporan: "Sudah Kirim", statusAudit: "Selesai" },

  // --- AGUSTUS 2025 ---
  { id: "agustus-2025-al-falah-depok", bulan: "Agustus", tahun: 2025, sekolahMitra: "Al-Falah Depok", tanggalKirim: "8-Dec-2025", statusLaporan: "Sudah Kirim", statusAudit: "Selesai" },
  { id: "agustus-2025-al-falah-klaten", bulan: "Agustus", tahun: 2025, sekolahMitra: "Al-Falah Klaten", tanggalKirim: "21-Nov-2025", statusLaporan: "Sudah Kirim", statusAudit: "Selesai" },
  { id: "agustus-2025-athaillah", bulan: "Agustus", tahun: 2025, sekolahMitra: "Athaillah", tanggalKirim: "27-Aug-2025", statusLaporan: "Sudah Kirim", statusAudit: "Selesai" },
  { id: "agustus-2025-cordova", bulan: "Agustus", tahun: 2025, sekolahMitra: "Cordova", tanggalKirim: "19-Nov-2025", statusLaporan: "Sudah Kirim", statusAudit: "Selesai" },
  { id: "agustus-2025-haura", bulan: "Agustus", tahun: 2025, sekolahMitra: "Haura", tanggalKirim: "27-Aug-2025", statusLaporan: "Sudah Kirim", statusAudit: "Selesai" },
  { id: "agustus-2025-ibnu-sina", bulan: "Agustus", tahun: 2025, sekolahMitra: "Ibnu Sina", tanggalKirim: "24-Oct-2025", statusLaporan: "Sudah Kirim", statusAudit: "Selesai" },
  { id: "agustus-2025-ideal", bulan: "Agustus", tahun: 2025, sekolahMitra: "Ideal", tanggalKirim: "3-Sep-2025", statusLaporan: "Sudah Kirim", statusAudit: "Selesai" },
  { id: "agustus-2025-kamila", bulan: "Agustus", tahun: 2025, sekolahMitra: "Kamila", tanggalKirim: "8-Jun-2026", statusLaporan: "Sudah Kirim", statusAudit: "Revisi" },
  { id: "agustus-2025-sma-lazuardi", bulan: "Agustus", tahun: 2025, sekolahMitra: "SMA Lazuardi", tanggalKirim: "", statusLaporan: "Belum Kirim", statusAudit: "-" },
  { id: "agustus-2025-tursina", bulan: "Agustus", tahun: 2025, sekolahMitra: "Tursina", tanggalKirim: "27-Nov-2025", statusLaporan: "Sudah Kirim", statusAudit: "Selesai" },

  // --- SEPTEMBER 2025 ---
  { id: "september-2025-al-falah-depok", bulan: "September", tahun: 2025, sekolahMitra: "Al-Falah Depok", tanggalKirim: "8-Dec-2025", statusLaporan: "Sudah Kirim", statusAudit: "Selesai" },
  { id: "september-2025-al-falah-klaten", bulan: "September", tahun: 2025, sekolahMitra: "Al-Falah Klaten", tanggalKirim: "21-Nov-2025", statusLaporan: "Sudah Kirim", statusAudit: "Selesai" },
  { id: "september-2025-athaillah", bulan: "September", tahun: 2025, sekolahMitra: "Athaillah", tanggalKirim: "26-Nov-2025", statusLaporan: "Sudah Kirim", statusAudit: "Selesai" },
  { id: "september-2025-cordova", bulan: "September", tahun: 2025, sekolahMitra: "Cordova", tanggalKirim: "19-Nov-2025", statusLaporan: "Sudah Kirim", statusAudit: "Selesai" },
  { id: "september-2025-haura", bulan: "September", tahun: 2025, sekolahMitra: "Haura", tanggalKirim: "9-Oct-2026", statusLaporan: "Sudah Kirim", statusAudit: "Selesai" },
  { id: "september-2025-ibnu-sina", bulan: "September", tahun: 2025, sekolahMitra: "Ibnu Sina", tanggalKirim: "24-Oct-2025", statusLaporan: "Sudah Kirim", statusAudit: "Selesai" },
  { id: "september-2025-ideal", bulan: "September", tahun: 2025, sekolahMitra: "Ideal", tanggalKirim: "25-Sep-2025", statusLaporan: "Sudah Kirim", statusAudit: "Selesai" },
  { id: "september-2025-kamila", bulan: "September", tahun: 2025, sekolahMitra: "Kamila", tanggalKirim: "8-Jun-2026", statusLaporan: "Sudah Kirim", statusAudit: "Revisi" },
  { id: "september-2025-sma-lazuardi", bulan: "September", tahun: 2025, sekolahMitra: "SMA Lazuardi", tanggalKirim: "", statusLaporan: "Belum Kirim", statusAudit: "-" },
  { id: "september-2025-tursina", bulan: "September", tahun: 2025, sekolahMitra: "Tursina", tanggalKirim: "27-Nov-2025", statusLaporan: "Sudah Kirim", statusAudit: "Selesai" },

  // --- OKTOBER 2025 ---
  { id: "oktober-2025-al-falah-depok", bulan: "Oktober", tahun: 2025, sekolahMitra: "Al-Falah Depok", tanggalKirim: "8-Dec-2025", statusLaporan: "Sudah Kirim", statusAudit: "Selesai" },
  { id: "oktober-2025-al-falah-klaten", bulan: "Oktober", tahun: 2025, sekolahMitra: "Al-Falah Klaten", tanggalKirim: "21-Nov-2025", statusLaporan: "Sudah Kirim", statusAudit: "Selesai" },
  { id: "oktober-2025-athaillah", bulan: "Oktober", tahun: 2025, sekolahMitra: "Athaillah", tanggalKirim: "14-Dec-2025", statusLaporan: "Sudah Kirim", statusAudit: "Selesai" },
  { id: "oktober-2025-cordova", bulan: "Oktober", tahun: 2025, sekolahMitra: "Cordova", tanggalKirim: "19-Nov-2025", statusLaporan: "Sudah Kirim", statusAudit: "Selesai" },
  { id: "oktober-2025-haura", bulan: "Oktober", tahun: 2025, sekolahMitra: "Haura", tanggalKirim: "4-Dec-2025", statusLaporan: "Sudah Kirim", statusAudit: "Selesai" },
  { id: "oktober-2025-ibnu-sina", bulan: "Oktober", tahun: 2025, sekolahMitra: "Ibnu Sina", tanggalKirim: "9-Dec-2025", statusLaporan: "Sudah Kirim", statusAudit: "Selesai" },
  { id: "oktober-2025-ideal", bulan: "Oktober", tahun: 2025, sekolahMitra: "Ideal", tanggalKirim: "", statusLaporan: "Belum Kirim", statusAudit: "-" },
  { id: "oktober-2025-kamila", bulan: "Oktober", tahun: 2025, sekolahMitra: "Kamila", tanggalKirim: "8-Jun-2026", statusLaporan: "Belum Kirim", statusAudit: "Revisi" },
  { id: "oktober-2025-sma-lazuardi", bulan: "Oktober", tahun: 2025, sekolahMitra: "SMA Lazuardi", tanggalKirim: "", statusLaporan: "Belum Kirim", statusAudit: "-" },
  { id: "oktober-2025-tursina", bulan: "Oktober", tahun: 2025, sekolahMitra: "Tursina", tanggalKirim: "27-Nov-2025", statusLaporan: "Sudah Kirim", statusAudit: "Selesai" },

  // --- NOVEMBER 2025 ---
  { id: "november-2025-al-falah-depok", bulan: "November", tahun: 2025, sekolahMitra: "Al-Falah Depok", tanggalKirim: "8-Dec-2025", statusLaporan: "Sudah Kirim", statusAudit: "Selesai" },
  { id: "november-2025-al-falah-klaten", bulan: "November", tahun: 2025, sekolahMitra: "Al-Falah Klaten", tanggalKirim: "8-May-2026", statusLaporan: "Sudah Kirim", statusAudit: "Selesai" },
  { id: "november-2025-athaillah", bulan: "November", tahun: 2025, sekolahMitra: "Athaillah", tanggalKirim: "14-Dec-2025", statusLaporan: "Sudah Kirim", statusAudit: "Selesai" },
  { id: "november-2025-cordova", bulan: "November", tahun: 2025, sekolahMitra: "Cordova", tanggalKirim: "16-Dec-2025", statusLaporan: "Sudah Kirim", statusAudit: "Selesai" },
  { id: "november-2025-haura", bulan: "November", tahun: 2025, sekolahMitra: "Haura", tanggalKirim: "4-Dec-2025", statusLaporan: "Sudah Kirim", statusAudit: "Selesai" },
  { id: "november-2025-ibnu-sina", bulan: "November", tahun: 2025, sekolahMitra: "Ibnu Sina", tanggalKirim: "9-Dec-2025", statusLaporan: "Sudah Kirim", statusAudit: "Selesai" },
  { id: "november-2025-ideal", bulan: "November", tahun: 2025, sekolahMitra: "Ideal", tanggalKirim: "", statusLaporan: "Belum Kirim", statusAudit: "-" },
  { id: "november-2025-kamila", bulan: "November", tahun: 2025, sekolahMitra: "Kamila", tanggalKirim: "8-Jun-2026", statusLaporan: "Sudah Kirim", statusAudit: "Revisi" },
  { id: "november-2025-sma-lazuardi", bulan: "November", tahun: 2025, sekolahMitra: "SMA Lazuardi", tanggalKirim: "", statusLaporan: "Belum Kirim", statusAudit: "-" },
  { id: "november-2025-tursina", bulan: "November", tahun: 2025, sekolahMitra: "Tursina", tanggalKirim: "1-Mar-2026", statusLaporan: "Sudah Kirim", statusAudit: "Selesai" },

  // --- DESEMBER 2025 ---
  { id: "desember-2025-al-falah-depok", bulan: "Desember", tahun: 2025, sekolahMitra: "Al-Falah Depok", tanggalKirim: "", statusLaporan: "Belum Kirim", statusAudit: "-" },
  { id: "desember-2025-al-falah-klaten", bulan: "Desember", tahun: 2025, sekolahMitra: "Al-Falah Klaten", tanggalKirim: "8-May-2026", statusLaporan: "Sudah Kirim", statusAudit: "Selesai" },
  { id: "desember-2025-athaillah", bulan: "Desember", tahun: 2025, sekolahMitra: "Athaillah", tanggalKirim: "4-Jan-2026", statusLaporan: "Sudah Kirim", statusAudit: "Selesai" },
  { id: "desember-2025-cordova", bulan: "Desember", tahun: 2025, sekolahMitra: "Cordova", tanggalKirim: "17-Jan-2026", statusLaporan: "Sudah Kirim", statusAudit: "Selesai" },
  { id: "desember-2025-haura", bulan: "Desember", tahun: 2025, sekolahMitra: "Haura", tanggalKirim: "12-Jan-2026", statusLaporan: "Sudah Kirim", statusAudit: "Selesai" },
  { id: "desember-2025-ibnu-sina", bulan: "Desember", tahun: 2025, sekolahMitra: "Ibnu Sina", tanggalKirim: "19-May-2026", statusLaporan: "Sudah Kirim", statusAudit: "Selesai" },
  { id: "desember-2025-ideal", bulan: "Desember", tahun: 2025, sekolahMitra: "Ideal", tanggalKirim: "", statusLaporan: "Belum Kirim", statusAudit: "-" },
  { id: "desember-2025-kamila", bulan: "Desember", tahun: 2025, sekolahMitra: "Kamila", tanggalKirim: "8-Jun-2026", statusLaporan: "Sudah Kirim", statusAudit: "Revisi" },
  { id: "desember-2025-sma-lazuardi", bulan: "Desember", tahun: 2025, sekolahMitra: "SMA Lazuardi", tanggalKirim: "", statusLaporan: "Belum Kirim", statusAudit: "-" },
  { id: "desember-2025-tursina", bulan: "Desember", tahun: 2025, sekolahMitra: "Tursina", tanggalKirim: "1-Mar-2026", statusLaporan: "Sudah Kirim", statusAudit: "Selesai" },

  // --- JANUARI 2026 ---
  { id: "januari-2026-al-falah-depok", bulan: "Januari", tahun: 2026, sekolahMitra: "Al-Falah Depok", tanggalKirim: "", statusLaporan: "Belum Kirim", statusAudit: "-" },
  { id: "januari-2026-al-falah-klaten", bulan: "Januari", tahun: 2026, sekolahMitra: "Al-Falah Klaten", tanggalKirim: "8-May-2026", statusLaporan: "Sudah Kirim", statusAudit: "Selesai" },
  { id: "januari-2026-athaillah", bulan: "Januari", tahun: 2026, sekolahMitra: "Athaillah", tanggalKirim: "", statusLaporan: "Belum Kirim", statusAudit: "-" },
  { id: "januari-2026-cordova", bulan: "Januari", tahun: 2026, sekolahMitra: "Cordova", tanggalKirim: "4-Mar-2026", statusLaporan: "Sudah Kirim", statusAudit: "Selesai" },
  { id: "januari-2026-haura", bulan: "Januari", tahun: 2026, sekolahMitra: "Haura", tanggalKirim: "26-Feb-2026", statusLaporan: "Sudah Kirim", statusAudit: "Selesai" },
  { id: "januari-2026-ibnu-sina", bulan: "Januari", tahun: 2026, sekolahMitra: "Ibnu Sina", tanggalKirim: "19-May-2026", statusLaporan: "Sudah Kirim", statusAudit: "Selesai" },
  { id: "januari-2026-ideal", bulan: "Januari", tahun: 2026, sekolahMitra: "Ideal", tanggalKirim: "", statusLaporan: "Belum Kirim", statusAudit: "-" },
  { id: "januari-2026-kamila", bulan: "Januari", tahun: 2026, sekolahMitra: "Kamila", tanggalKirim: "8-Jun-2026", statusLaporan: "Sudah Kirim", statusAudit: "Revisi" },
  { id: "januari-2026-sma-lazuardi", bulan: "Januari", tahun: 2026, sekolahMitra: "SMA Lazuardi", tanggalKirim: "2-Jun-2026", statusLaporan: "Sudah Kirim", statusAudit: "Selesai" },
  { id: "januari-2026-tursina", bulan: "Januari", tahun: 2026, sekolahMitra: "Tursina", tanggalKirim: "1-Mar-2026", statusLaporan: "Sudah Kirim", statusAudit: "Selesai" },

  // --- FEBRUARI 2026 ---
  { id: "februari-2026-al-falah-depok", bulan: "Februari", tahun: 2026, sekolahMitra: "Al-Falah Depok", tanggalKirim: "", statusLaporan: "Belum Kirim", statusAudit: "-" },
  { id: "februari-2026-al-falah-klaten", bulan: "Februari", tahun: 2026, sekolahMitra: "Al-Falah Klaten", tanggalKirim: "8-May-2026", statusLaporan: "Sudah Kirim", statusAudit: "Selesai" },
  { id: "februari-2026-athaillah", bulan: "Februari", tahun: 2026, sekolahMitra: "Athaillah", tanggalKirim: "", statusLaporan: "Belum Kirim", statusAudit: "-" },
  { id: "februari-2026-cordova", bulan: "Februari", tahun: 2026, sekolahMitra: "Cordova", tanggalKirim: "18-May-2026", statusLaporan: "Sudah Kirim", statusAudit: "Selesai" },
  { id: "februari-2026-haura", bulan: "Februari", tahun: 2026, sekolahMitra: "Haura", tanggalKirim: "26-Feb-2026", statusLaporan: "Sudah Kirim", statusAudit: "Selesai" },
  { id: "februari-2026-ibnu-sina", bulan: "Februari", tahun: 2026, sekolahMitra: "Ibnu Sina", tanggalKirim: "19-May-2026", statusLaporan: "Sudah Kirim", statusAudit: "Selesai" },
  { id: "februari-2026-ideal", bulan: "Februari", tahun: 2026, sekolahMitra: "Ideal", tanggalKirim: "", statusLaporan: "Belum Kirim", statusAudit: "-" },
  { id: "februari-2026-kamila", bulan: "Februari", tahun: 2026, sekolahMitra: "Kamila", tanggalKirim: "8-Jun-2026", statusLaporan: "Sudah Kirim", statusAudit: "Revisi" },
  { id: "februari-2026-sma-lazuardi", bulan: "Februari", tahun: 2026, sekolahMitra: "SMA Lazuardi", tanggalKirim: "2-Jun-2026", statusLaporan: "Sudah Kirim", statusAudit: "Selesai" },
  { id: "februari-2026-tursina", bulan: "Februari", tahun: 2026, sekolahMitra: "Tursina", tanggalKirim: "1-Mar-2026", statusLaporan: "Sudah Kirim", statusAudit: "Selesai" },

  // --- MARET 2026 ---
  { id: "maret-2026-al-falah-depok", bulan: "Maret", tahun: 2026, sekolahMitra: "Al-Falah Depok", tanggalKirim: "", statusLaporan: "Belum Kirim", statusAudit: "-" },
  { id: "maret-2026-al-falah-klaten", bulan: "Maret", tahun: 2026, sekolahMitra: "Al-Falah Klaten", tanggalKirim: "8-May-2026", statusLaporan: "Sudah Kirim", statusAudit: "Selesai" },
  { id: "maret-2026-athaillah", bulan: "Maret", tahun: 2026, sekolahMitra: "Athaillah", tanggalKirim: "31-Mar-2026", statusLaporan: "Sudah Kirim", statusAudit: "Selesai" },
  { id: "maret-2026-cordova", bulan: "Maret", tahun: 2026, sekolahMitra: "Cordova", tanggalKirim: "26-May-2026", statusLaporan: "Sudah Kirim", statusAudit: "Selesai" },
  { id: "maret-2026-haura", bulan: "Maret", tahun: 2026, sekolahMitra: "Haura", tanggalKirim: "", statusLaporan: "Belum Kirim", statusAudit: "-" },
  { id: "maret-2026-ibnu-sina", bulan: "Maret", tahun: 2026, sekolahMitra: "Ibnu Sina", tanggalKirim: "19-May-2026", statusLaporan: "Sudah Kirim", statusAudit: "Selesai" },
  { id: "maret-2026-ideal", bulan: "Maret", tahun: 2026, sekolahMitra: "Ideal", tanggalKirim: "", statusLaporan: "Belum Kirim", statusAudit: "-" },
  { id: "maret-2026-kamila", bulan: "Maret", tahun: 2026, sekolahMitra: "Kamila", tanggalKirim: "8-Jun-2026", statusLaporan: "Sudah Kirim", statusAudit: "Revisi" },
  { id: "maret-2026-sma-lazuardi", bulan: "Maret", tahun: 2026, sekolahMitra: "SMA Lazuardi", tanggalKirim: "2-Jun-2026", statusLaporan: "Sudah Kirim", statusAudit: "Selesai" },
  { id: "maret-2026-tursina", bulan: "Maret", tahun: 2026, sekolahMitra: "Tursina", tanggalKirim: "13-May-2026", statusLaporan: "Sudah Kirim", statusAudit: "Selesai" },

  // --- APRIL 2026 ---
  { id: "april-2026-al-falah-depok", bulan: "April", tahun: 2026, sekolahMitra: "Al-Falah Depok", tanggalKirim: "", statusLaporan: "Belum Kirim", statusAudit: "-" },
  { id: "april-2026-al-falah-klaten", bulan: "April", tahun: 2026, sekolahMitra: "Al-Falah Klaten", tanggalKirim: "8-May-2026", statusLaporan: "Sudah Kirim", statusAudit: "Selesai" },
  { id: "april-2026-athaillah", bulan: "April", tahun: 2026, sekolahMitra: "Athaillah", tanggalKirim: "28-Apr-2026", statusLaporan: "Sudah Kirim", statusAudit: "Selesai" },
  { id: "april-2026-cordova", bulan: "April", tahun: 2026, sekolahMitra: "Cordova", tanggalKirim: "8-May-2026", statusLaporan: "Sudah Kirim", statusAudit: "Selesai" },
  { id: "april-2026-haura", bulan: "April", tahun: 2026, sekolahMitra: "Haura", tanggalKirim: "", statusLaporan: "Belum Kirim", statusAudit: "-" },
  { id: "april-2026-ibnu-sina", bulan: "April", tahun: 2026, sekolahMitra: "Ibnu Sina", tanggalKirim: "19-May-2026", statusLaporan: "Sudah Kirim", statusAudit: "Selesai" },
  { id: "april-2026-ideal", bulan: "April", tahun: 2026, sekolahMitra: "Ideal", tanggalKirim: "", statusLaporan: "Belum Kirim", statusAudit: "-" },
  { id: "april-2026-kamila", bulan: "April", tahun: 2026, sekolahMitra: "Kamila", tanggalKirim: "8-Jun-2026", statusLaporan: "Sudah Kirim", statusAudit: "Revisi" },
  { id: "april-2026-sma-lazuardi", bulan: "April", tahun: 2026, sekolahMitra: "SMA Lazuardi", tanggalKirim: "2-Jun-2026", statusLaporan: "Sudah Kirim", statusAudit: "Selesai" },
  { id: "april-2026-tursina", bulan: "April", tahun: 2026, sekolahMitra: "Tursina", tanggalKirim: "13-May-2026", statusLaporan: "Sudah Kirim", statusAudit: "Selesai" },

  // --- MEI 2026 ---
  { id: "mei-2026-al-falah-depok", bulan: "Mei", tahun: 2026, sekolahMitra: "Al-Falah Depok", tanggalKirim: "", statusLaporan: "Belum Kirim", statusAudit: "-" },
  { id: "mei-2026-al-falah-klaten", bulan: "Mei", tahun: 2026, sekolahMitra: "Al-Falah Klaten", tanggalKirim: "", statusLaporan: "Belum Kirim", statusAudit: "-" },
  { id: "mei-2026-athaillah", bulan: "Mei", tahun: 2026, sekolahMitra: "Athaillah", tanggalKirim: "", statusLaporan: "Belum Kirim", statusAudit: "-" },
  { id: "mei-2026-cordova", bulan: "Mei", tahun: 2026, sekolahMitra: "Cordova", tanggalKirim: "", statusLaporan: "Belum Kirim", statusAudit: "-" },
  { id: "mei-2026-haura", bulan: "Mei", tahun: 2026, sekolahMitra: "Haura", tanggalKirim: "", statusLaporan: "Belum Kirim", statusAudit: "-" },
  { id: "mei-2026-ibnu-sina", bulan: "Mei", tahun: 2026, sekolahMitra: "Ibnu Sina", tanggalKirim: "19-May-2026", statusLaporan: "Sudah Kirim", statusAudit: "Selesai" },
  { id: "mei-2026-ideal", bulan: "Mei", tahun: 2026, sekolahMitra: "Ideal", tanggalKirim: "", statusLaporan: "Belum Kirim", statusAudit: "-" },
  { id: "mei-2026-kamila", bulan: "Mei", tahun: 2026, sekolahMitra: "Kamila", tanggalKirim: "8-Jun-2026", statusLaporan: "Sudah Kirim", statusAudit: "Revisi" },
  { id: "mei-2026-sma-lazuardi", bulan: "Mei", tahun: 2026, sekolahMitra: "SMA Lazuardi", tanggalKirim: "2-Jun-2026", statusLaporan: "Sudah Kirim", statusAudit: "Selesai" },
  { id: "mei-2026-tursina", bulan: "Mei", tahun: 2026, sekolahMitra: "Tursina", tanggalKirim: "", statusLaporan: "Belum Kirim", statusAudit: "-" },
];

export const fallbackKPIs: KPIMitra[] = [
  {
    id: "kpi-1-1-fb",
    idKpi: "1.1",
    kategori: "Strategic Alignment",
    kpi: "Roadmap Coverage",
    program: "LATOF Akademik, LATOF Bisnis, RAKER",
    target: 100,
    realisasi: 85,
    satuan: "%",
    progress: 85,
    tahunAjaran: "2025/2026"
  },
  {
    id: "kpi-1-2-fb",
    idKpi: "1.2",
    kategori: "Governance",
    kpi: "Governance Review",
    program: "Internal Audit Review",
    target: 100,
    realisasi: 60,
    satuan: "%",
    progress: 60,
    tahunAjaran: "2025/2026"
  },
  {
    id: "kpi-1-3-fb",
    idKpi: "1.3",
    kategori: "Data & Dashboard",
    kpi: "Data Submission",
    program: "Dashboard Mitra",
    target: 100,
    realisasi: 95,
    satuan: "%",
    progress: 95,
    tahunAjaran: "2025/2026"
  },
  {
    id: "kpi-1-4-fb",
    idKpi: "1.4",
    kategori: "Financial",
    kpi: "Financial Report",
    program: "Laporan Bulanan",
    target: 100,
    realisasi: 90,
    satuan: "%",
    progress: 90,
    tahunAjaran: "2025/2026"
  },
  {
    id: "kpi-2-1-fb",
    idKpi: "2.1",
    kategori: "Partner Support",
    kpi: "SLA Compliance",
    program: "Visitasi, Magang, Control Alignment Visitasi, Control Alignment Magang",
    target: 100,
    realisasi: 75,
    satuan: "%",
    progress: 75,
    tahunAjaran: "2025/2026"
  },
  {
    id: "kpi-2-2-fb",
    idKpi: "2.2",
    kategori: "Needs Development",
    kpi: "JNA Coverage",
    program: "LATOF Akademik, LATOF Bisnis, RAKER",
    target: 100,
    realisasi: 50,
    satuan: "%",
    progress: 50,
    tahunAjaran: "2024/2025"
  },
  {
    id: "kpi-2-3-fb",
    idKpi: "2.3",
    kategori: "MER",
    kpi: "MER Timeliness",
    program: "Progression Test, Checkpoint Test, Konsultasi Mitra",
    target: 100,
    realisasi: 100,
    satuan: "%",
    progress: 100,
    tahunAjaran: "2024/2025"
  },
  {
    id: "kpi-2-4-fb",
    idKpi: "2.4",
    kategori: "Project Management",
    kpi: "Project Delivery",
    program: "Visitasi, Magang, Control Alignment Visitasi & Magang",
    target: 100,
    realisasi: 40,
    satuan: "%",
    progress: 40,
    tahunAjaran: "2023/2024"
  },
  {
    id: "kpi-2-5-fb",
    idKpi: "2.5",
    kategori: "Program Quality",
    kpi: "Program Execution",
    program: "SPARK, STEP UP, ToT Coach , Training Best Practice",
    target: 100,
    realisasi: 100,
    satuan: "%",
    progress: 100,
    tahunAjaran: "2023/2024"
  },
  {
    id: "kpi-3-1-fb",
    idKpi: "3.1",
    kategori: "Ethics",
    kpi: "Complaint Resolution",
    program: "Konsultasi Aliansi Mitra Pusat",
    target: 100,
    realisasi: 100,
    satuan: "%",
    progress: 100,
    tahunAjaran: "2022/2023"
  }
];

